spring.datasource.url=${jdbc:mysql://mys.railway.internal:3312/raelway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}

spring.datasource.username=${roool}

spring.datasource.password=${yjVAOVWslQqhsMATomVHNIAsoCBBvl}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

server.port=${PORT:8080}